# Generated by Django 5.1.7 on 2025-03-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_app', '0002_campaign_chatlog_socialmediapost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='state',
            field=models.CharField(default='start', max_length=50),
        ),
    ]
